export const metadata = {
  title: 'Privacy Policy — aigeek.ink',
  description: 'Privacy Policy for aigeek.ink',
}

export default function Privacy() {
  return (
    <main style={{ fontFamily: 'system-ui, -apple-system, sans-serif', maxWidth: '680px', margin: '0 auto', padding: '2rem 1.5rem' }}>
      <nav style={{ marginBottom: '2rem' }}>
        <a href="/" style={{ fontSize: '0.9rem', color: '#555', textDecoration: 'none' }}>← aigeek.ink</a>
      </nav>
      <h1 style={{ fontSize: '1.8rem', fontWeight: '700', marginBottom: '0.5rem', color: '#111' }}>Privacy Policy</h1>
      <p style={{ fontSize: '0.85rem', color: '#888', marginBottom: '2rem' }}>Last updated: June 2026</p>

      <section style={{ lineHeight: '1.8', color: '#333' }}>
        <h2 style={{ fontSize: '1.1rem', fontWeight: '600', margin: '1.5rem 0 0.5rem', color: '#111' }}>Our Privacy Promise</h2>
        <p>Your privacy is not an afterthought at aigeek.ink — it is a core part of the product. We built this tool knowing that people upload body photos, and we take that trust seriously.</p>

        <h2 style={{ fontSize: '1.1rem', fontWeight: '600', margin: '1.5rem 0 0.5rem', color: '#111' }}>What We Collect</h2>
        <p><strong>Account information:</strong> Email address when you sign up or join the waitlist.</p>
        <p style={{ marginTop: '0.5rem' }}><strong>Photos you upload:</strong> Body photos you upload for the skin preview feature. These are stored in a private, access-controlled environment and are never publicly visible.</p>
        <p style={{ marginTop: '0.5rem' }}><strong>Generated designs:</strong> Tattoo designs generated by your prompts, stored to deliver the Service to you.</p>
        <p style={{ marginTop: '0.5rem' }}><strong>Payment information:</strong> We do not store payment card details. All payment processing is handled by our payment provider.</p>
        <p style={{ marginTop: '0.5rem' }}><strong>Usage data:</strong> Basic analytics such as pages visited and features used, collected via Google Analytics.</p>

        <h2 style={{ fontSize: '1.1rem', fontWeight: '600', margin: '1.5rem 0 0.5rem', color: '#111' }}>How We Use Your Data</h2>
        <p>We use your data solely to deliver and improve the Service. We do not sell your data. We do not share your data with third parties except as necessary to operate the Service (payment processing, cloud storage, analytics).</p>

        <h2 style={{ fontSize: '1.1rem', fontWeight: '600', margin: '1.5rem 0 0.5rem', color: '#111' }}>Your Photos — Specific Commitments</h2>
        <ul style={{ paddingLeft: '1.5rem', marginTop: '0.5rem' }}>
          <li>Body photos are automatically deleted after 72 hours.</li>
          <li>You can delete your uploaded photos at any time from your account settings.</li>
          <li>Photos are stored in private buckets — never publicly accessible via URL.</li>
          <li>We do not use your photos to train AI models.</li>
          <li>We do not use your photos in marketing materials without your explicit written consent.</li>
        </ul>

        <h2 style={{ fontSize: '1.1rem', fontWeight: '600', margin: '1.5rem 0 0.5rem', color: '#111' }}>Cookies</h2>
        <p>We use essential cookies to keep you logged in and to process payments. We use Google Analytics cookies to understand how people use the site. You can disable cookies in your browser settings, though some features may not work correctly.</p>

        <h2 style={{ fontSize: '1.1rem', fontWeight: '600', margin: '1.5rem 0 0.5rem', color: '#111' }}>Data Retention</h2>
        <p>Account data is retained while your account is active. Uploaded photos are deleted after 72 hours or immediately upon your request. You may request deletion of your entire account and associated data at any time by emailing us.</p>

        <h2 style={{ fontSize: '1.1rem', fontWeight: '600', margin: '1.5rem 0 0.5rem', color: '#111' }}>Your Rights</h2>
        <p>You have the right to access, correct, or delete your personal data at any time. To exercise these rights, email us at <a href="mailto:aigeek.ink@gmail.com" style={{ color: '#111' }}>aigeek.ink@gmail.com</a>.</p>

        <h2 style={{ fontSize: '1.1rem', fontWeight: '600', margin: '1.5rem 0 0.5rem', color: '#111' }}>Changes to This Policy</h2>
        <p>We may update this policy from time to time. We will notify registered users of significant changes by email.</p>

        <h2 style={{ fontSize: '1.1rem', fontWeight: '600', margin: '1.5rem 0 0.5rem', color: '#111' }}>Contact</h2>
        <p>Privacy questions or data requests: <a href="mailto:aigeek.ink@gmail.com" style={{ color: '#111' }}>aigeek.ink@gmail.com</a></p>
      </section>
    </main>
  )
}
