export const metadata = {
  title: 'Terms of Service — aigeek.ink',
  description: 'Terms of Service for aigeek.ink',
}

export default function Terms() {
  return (
    <main style={{ fontFamily: 'system-ui, -apple-system, sans-serif', maxWidth: '680px', margin: '0 auto', padding: '2rem 1.5rem' }}>
      <nav style={{ marginBottom: '2rem' }}>
        <a href="/" style={{ fontSize: '0.9rem', color: '#555', textDecoration: 'none' }}>← aigeek.ink</a>
      </nav>
      <h1 style={{ fontSize: '1.8rem', fontWeight: '700', marginBottom: '0.5rem', color: '#111' }}>Terms of Service</h1>
      <p style={{ fontSize: '0.85rem', color: '#888', marginBottom: '2rem' }}>Last updated: June 2026</p>

      <section style={{ lineHeight: '1.8', color: '#333' }}>
        <h2 style={{ fontSize: '1.1rem', fontWeight: '600', margin: '1.5rem 0 0.5rem', color: '#111' }}>1. Acceptance of Terms</h2>
        <p>By accessing or using aigeek.ink ("the Service"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.</p>

        <h2 style={{ fontSize: '1.1rem', fontWeight: '600', margin: '1.5rem 0 0.5rem', color: '#111' }}>2. Description of Service</h2>
        <p>aigeek.ink is an AI-powered tattoo planning tool. The Service allows users to generate tattoo design concepts, preview designs on uploaded photos, and download printable stencils and reference documents. All designs are AI-generated and intended as planning references only.</p>

        <h2 style={{ fontSize: '1.1rem', fontWeight: '600', margin: '1.5rem 0 0.5rem', color: '#111' }}>3. Payments</h2>
        <p>The Service offers one-time purchases only. There are no subscriptions or recurring charges. All payments are processed securely by our payment provider. Prices are listed in USD. By completing a purchase, you authorise the stated charge.</p>

        <h2 style={{ fontSize: '1.1rem', fontWeight: '600', margin: '1.5rem 0 0.5rem', color: '#111' }}>4. AI-Generated Content</h2>
        <p>Designs generated by the Service are produced by artificial intelligence based on your text prompts. aigeek.ink does not guarantee that any generated design is original, unique, or free from similarity to existing works. Generated designs are provided as creative references for tattoo planning purposes only. You are responsible for working with your tattoo artist to refine any design before it is applied to skin.</p>

        <h2 style={{ fontSize: '1.1rem', fontWeight: '600', margin: '1.5rem 0 0.5rem', color: '#111' }}>5. Medical Disclaimer</h2>
        <p>aigeek.ink is a design planning tool only. We are not medical professionals. Tattoo application involves skin procedures — consult a licensed professional tattoo artist. We accept no responsibility for any tattoo applied based on designs generated by the Service.</p>

        <h2 style={{ fontSize: '1.1rem', fontWeight: '600', margin: '1.5rem 0 0.5rem', color: '#111' }}>6. User Content</h2>
        <p>You retain ownership of photos you upload. By uploading a photo, you grant aigeek.ink a limited licence to process that photo solely to deliver the Service to you. We do not use your photos to train AI models. Photos are automatically deleted after 72 hours.</p>

        <h2 style={{ fontSize: '1.1rem', fontWeight: '600', margin: '1.5rem 0 0.5rem', color: '#111' }}>7. Prohibited Use</h2>
        <p>You may not use the Service to generate content that is illegal, hateful, sexually explicit, or that infringes on the rights of others. We reserve the right to terminate accounts that violate these terms.</p>

        <h2 style={{ fontSize: '1.1rem', fontWeight: '600', margin: '1.5rem 0 0.5rem', color: '#111' }}>8. Limitation of Liability</h2>
        <p>To the maximum extent permitted by law, aigeek.ink shall not be liable for any indirect, incidental, or consequential damages arising from your use of the Service. Our total liability shall not exceed the amount you paid for the Service.</p>

        <h2 style={{ fontSize: '1.1rem', fontWeight: '600', margin: '1.5rem 0 0.5rem', color: '#111' }}>9. Changes to Terms</h2>
        <p>We may update these terms at any time. Continued use of the Service after changes constitutes acceptance of the new terms.</p>

        <h2 style={{ fontSize: '1.1rem', fontWeight: '600', margin: '1.5rem 0 0.5rem', color: '#111' }}>10. Contact</h2>
        <p>Questions about these terms? Email us at <a href="mailto:aigeek.ink@gmail.com" style={{ color: '#111' }}>aigeek.ink@gmail.com</a></p>
      </section>
    </main>
  )
}
